name: .NET Core (build)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      BUILD_RERUN_COUNT: ${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@main

    - name: Install latest .NET 6 SDK
      uses: Elskom/setup-latest-dotnet@main
      with:
        VERSION_MAJOR: '6'
        VERSION_BAND: '2xx'

    - name: Install Elskom workload
      uses: nick-invision/retry@master
      with:
        timeout_minutes: 2
        max_attempts: 50
        retry_on: error
        command: |
          dotnet tool restore
          dotnet tool run elskom-check -- install # this will install the entire workload.

    - name: Restore, Build, and pack
      uses: Elskom/build-dotnet@main
      with:
        RESTORE: false
        PACK: true
        PUSH: true
