name: .NET Core (build pull request)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      BUILD_RERUN_COUNT: ${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@main

    - name: Install latest .NET SDK
      uses: Elskom/setup-latest-dotnet@main
      with:
        SDK_VERSION: '7.0.100-rc.1.22431.12'
        RUNTIME_VERSIONS: ''

    - name: Restore, Build, and pack
      uses: Elskom/build-dotnet@main
      with:
        RESTORE: false
