name: .NET Core (build)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@main
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive

    - name: Install latest .NET SDK
      uses: Elskom/setup-latest-dotnet@main

    - name: Restore, Build, and pack
      uses: Elskom/build-dotnet@main
      with:
        RESTORE: false
